<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RestaurantMenu.Business\RestaurantMenu.Business.csproj" />
    <ProjectReference Include="..\RestaurantMenu.DataAccess\RestaurantMenu.DataAccess.csproj" />
    <ProjectReference Include="..\RestaurantMenu.Entities\RestaurantMenu.Entities.csproj" />
  </ItemGroup>

</Project>
